### ISSUE TITLE
Automatically delete bags that fail any validation

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/project_electron_transfer#36]

**Comment by helrond** [comment]
Can someone from @RockefellerArchiveCenter/marist confirm/point to code that does this?

**Comment by dboutmybizness** [comment]
Bags are being deleted at the end of the process.  TO verify you'd need to be look in the processing DIR of uploading org.  So /data/orgX/processing.  Currently files are removed either way.
