### ISSUE TITLE
Correctly message bags with invalid filenames in UI

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/project_electron_transfer#47]
Currently, bag names containing an illegal character do not appear in UI (although data indicating transfer date/time/user does)

**Comment by helrond** [comment]
Also appears that these bags are not moved/deleted from`upload/` directory

**Comment by dboutmybizness** [comment]
@helrond that name in the UI, represents the bag name or the attempted bag name.. Since, the filename was invalid, i don't consider it to be a bag.. would you like me to store whatever the filename was inline with the bag name field

**Comment by helrond** [comment]
@dboutmybizness yes, I think we want to record every attempted transfer, so that if a donor logs in they can clearly see what was accepted, what was not, and why, regardless of whether or not the bag was kept or deleted.

**Comment by dboutmybizness** [comment]
Also seems like we are at the point where the report should deliver clarity on why the bag failed.. You agree?

**Comment by dboutmybizness** [comment]
@helrond the path is stored, so i have the attempted filename.. The field thats being populated is just the bag name..

**Comment by helrond** [comment]
@dboutmybizness yes I do. I think we should display a short status in the list view, and the detail view for each transfer should contain the details of why it failed.

**Comment by dboutmybizness** [comment]
Okay, will get that all hooked up.

**Comment by helrond** [comment]
Fixed by 1a38e4a7611bef12765f6cff240a8da9e0384001
